#+TITLE: Polyglossia
* Foreign Language Education
* Why Study Another Language?
Studying one (or more) foreign language opens up the world to you.
* Particular Languages
* Lingua Latina
* Le Francais
I find it quite useful when reading about current events around the world.  Although I am not good at spoken French, I can understand the gist of written text.
* 日本語
Japanese is a 
* Motivation to Study
* Studying Through Pop Culture
#+begin_center
yt:LsghDF1OUSQ

I watch my favorite TV shows and movies in Japanese
#+end_center
* Studying Through Video Games
#+begin_center
yt:LcRjtfByqHk

I frequently play Star Wars: The Old Republic /en français/ to keep my comprehension skills from getting rusty.
#+end_center
Although playing an entirely new game in a foreign language can be scary, it can be quite an educational experience to play a game you are quite familiar with.  I have been playing /Star Wars: the Old Republic/ on and off since it came out in 2011.  Starting in 2021, I began playing it in French.


Video games are perhaps one of the easiest methods of engaging with a foreign language.  Although in the past it was quite difficult to find foreign language editions of games, most modern games have the option to switch languages.  Failing that, the installer will usually prompt the user, asking which language it should be installed in.

#+begin_center
yt:0a_Vhd8FjUM

I also play Halo in Japanese.
#+end_center
* Studying Through Music
#+begin_center


I study 
#+end_center

I also study Gregorian chant.

* Studying Through Studying
Studying is not limited to textbooks.

For example, when I study the Bible and early Christian literature, I frequently do so in English, but also in Latin and Greek.  It is very useful to have a second or third opinion of a difficult passage.  With regard to Patristic literature, many texts have never been translated into English, so a grasp of those languages is rather useful.

I also sometimes make use of foreign language textbooks, such as this Japanese reader of Cicero's /Somnium Scipionis/.
