#+macro: ruby @@html:<ruby> $1<rp>(</rp><rt>$2</rt><rp>)</rp></ruby>@@@@latex:\ruby{$1}{$2}@@
#+TITLE: 島のブルース
* Shima no Blues
#+begin_center
[[yt:2dMVNAHaz7Q]]
#+begin_quote
Original audio recording by Misawa Akemi ft. the Mahina Stars with lyrics written in romaji.
#+end_quote
#+end_center
One of the most famous /shin-min’yo/ songs, 「({{{ruby(島,Shima)}}}{{{ruby(の,no)}}}{{{ruby(ブルース,Blues)}}})」 by  {{{ruby(三沢,Misawa)}}}{{{ruby(あけみ,Akemi)}}} is a beloved ballad that evokes a yearning for the Amami islands. The original recording by Misawa ft. Hiroshi Wada & His Mahina Stars opens with traditional {{{ruby(手笛,tebue)}}} (finger whistling) and “rum-tum-tum” drumming which accompany shima-uta performances.

#+begin_center
[[yt:35Cyh7G1_oE]]
#+begin_quote
Mitsuwa Akemi performs at the 14th annual /Kohaku Uta Gassen/ New Years’ song contest.
#+end_quote
#+end_center

In 1963, she won the Rookie Artist award and was invited to perform at NHK’s annual /Kohaku Uta Gassen/ New Year’s song contest. Performing on the Red Team alongside Asaoka Yusaji who sang another /shin-min’yo/ song “[[https://www.youtube.com/watch?v=rwKcxyWfAnw][Erabu Yuri no Hana]],” from the Amami archipelago. It is a popular song for the shamisen. Tanaka Atsushi has a (Japanese) [[https://www.youtube.com/watch?v=iAcUKx-FRPs][tutorial on YouTube]] teaching how to play it on an Okinawan /sanshin/.
* Lyrics
As a shin-min’yo song, the lyrics are likely still under copyright, but in place of the actual words I have provided their rough meaning below. This is of course an amateur translation, but I feel I’ve gotten the feeling of the song across.

| I can't help but think of Amami under the shade of these sago palms        |
| I think I might cry and start shaking like shell ginger caught in the wind |
| With streaming  black hair, I look just like an island girl                |
| You know I'm an island girl                                                |
|                                                                            |
| Is my sweetheart still awake, or has he already gone to bed?               |
| I'm starting to feel like a plover all alone on this beach                 |
| The southern winds are blowing tonight and I can't sleep                   |
| I can't sleep at all                                                       |
|                                                                            |
| The summer dance lasts for seven days and seven nights                     |
| Everyone you know is there, and tonight the moon is shining                |
| Look to Naze and you'll see a boat in the harbor                           |
| It's just setting out now                                                  |
|                                                                            |
| I want to dress up in my Oshima silk just for him                          |
| He'll never get that image out of his head                                 |
| I'll always be his island girl                                             |
| His loveable island girl                                                   |
Notes:
1. As far as I’m aware, {{{ruby(南風,hae)}}}, the southern wind, brings rough, warm weather, as well as typhoons, from the south. In standard dialect, it is pronounced “/minami kaze/.”
2. Oshima silk is one of the distinctive goods produced on Amami-Oshima. It is high quality and prized for its high quality throughout Japan.
3. /kana/ (加那 or 愛人) means "beloved" or "lover" in the local dialect.

{{{ruby(蘇鉄,sotetsu)}}} is the Japanese name of /cycas revoluta/, the King Sago palm. They are everywhere in the Amami islands. Kanami village on Tokunoshima island has a “cycad tunnel,” where one can enjoy a leisurely walk under the shade of the sago palms. They are kept as decorative plants, but historically they were kept to serve as food in times of famine. Though the entire plant is toxic, parts of it can be ground up and washed of their toxin, allowing it to be eaten safely.  The folk song 「[[https://www.youtube.com/watch?v=XCcpF986JlM][{{{ruby(豊年,hounen)}}}{{{ruby(節,bushi)}}}]]」 concerns this, where, upon hearing news that a rice shipment from the mainland has sunk, villagers go out and cut down the sotetsu for cooking. Sago flour is still sometimes used today as an ingredient in pancakes.

Shell ginger, called sanen in the Amami dialect, is a planet widely used in Ryukyuan culture. It is used to wrap mochi (rice cakes) and to brew tea, and is credited with promoting healthy skin and longevity. The song “Dondon Bushi” (or “[[https://www.youtube.com/watch?v=Y_2cA0xQ3KY][Muchi Tabore]]“) is sung by children as they [[https://www.youtube.com/watch?v=b4Nkj_kLRDg][canvas the town]], asking for rice cakes which are wrapped in the leaves of this plant.

Although black hair is ubiquitous in east Asia, it is a very common descriptor of a beautiful girl or woman. Long and flowing black hair, sometimes going as far as the waist, is a particular mark of beauty.

Plovers are a common sight on the beaches of the Amami archipelago.

Although many know of the Japanese /(O)bon/ festival, it is celebrated at different times in different regions. In the Amami islands, it is known as {{{ruby(八月,hachigatsu)}}}{{{ruby(踊り,odori)}}} (the August Dance). Although there is a great deal of similarity with the culture of nearby Okinawa, eisa is not traditionally performed as part of the festivities, but instead local [[https://youtu.be/pFJs-vDajt4?t=763][/hachigatsu-odori-uta/]].

[[https://www.youtube.com/watch?v=muLirCQOlo4][Oshima Tsumugi]] is a type of silk pongee and is one of the principal goods unique to the island. In the mid-20th century, when this song was produced, many women were employed as weavers. Unfortunately, the craft is endangered, with only a handful of companies producing the fabric. While men’s kimonos are handsome with a rich indigo color or earthy tone color either solid or in subdued pattern, women’s kimonos feature elaborate and quite striking designs.

Not too long ago, I was visiting Amami-Oshima with a couple friends and we stopped by a hotel to rent a car for the weekend. To my surprise, I saw a familiar face in the lobby. Who was it but Akemi Misawa! Among the various items in the collection was what appears to be the kimono she wore to the 14th Kohaku Uta Gassen.

Credits
Lyrics by {{{ruby(吉川,Yoshikawa)}}}{{{ruby(静夫,Shizuo)}}}, composed by {{{ruby(渡久地,Tokuchi)}}}{{{ruby(政信,Masanobu)}}}, originally performed by {{{ruby(三沢,Misawa)}}}{{{ruby(あけみ,Akemi)}}} and Hiroshi Wada & His Mahina Stars (和田弘とマヒナスターズ)

It can be found on Misawa’s various “Best of” albums, as well as part of the /Amami Shin-min’yo Masterpiece Collection: Shima no Blues/ ([[https://www.simauta.net/sinminyo.html][奄美新民謡名曲集CD「島のブルース」]]) .
