#+TITLE: STVDIA·CLASSICA
* Studia Classica
Classical Studies are the heart of a humanistic education. There are may different types of curricula worthy of following, and they each have their own value.
* What is the West?
The “West” is ultimately an arbitrary but and inexact category, but in its narrowest definition, it is generally held to refer to the legacy held in common by the nations of Europe, and their successors, that were historically shaped by Latin Christianity (Roman Catholic and, later, Protestant). A more broad definition encompasses all nations whose identities were profoundly shaped by ancient Greek and/or Roman culture. However, cultural legacies are passed down and transmitted to various peoples with little regard for geography. Does it include (modern) Greece? Russia? Turkey? Egypt? Brazil? The identities of these countries are all profoundly influenced by the ancient Greeks and Romans.
* What are the Classics?
The Classics are literary works that are the best suited as a foundation for a well-rounded education. This does not mean that the ideas contained within are the best by any objective or moral standpoint, nor does it mean that we ought to agree with them. It means that they are influential, provocative, and have stood the test of time.

In a more technical sense, it usually refers to the study of Greco-Roman civilization, culture, and language during the Classical period (8th c. BC – 6th c. AD), which was a golden age of sorts that ends with the societal fragmentation resulting from the decline and collapse of the western half of the Roman Empire. Over many centuries, these fragmented societies and cultures coalesced into the nation-states we known and recognize today.

The Bible, a collection of Hebrew and Greek texts compiled over the course of a thousand years with oral traditions dating back thousands more, is the core of the Western Canon. Touted by promoters as “the best-selling book in history,” it is an essential text for anyone, believer and non-believer alike, seeking to understand the culture and history of the Western world. Many familiar with the Bible also become interested in Classical Studies as a way to better understand the contexts in which it was written and read.

Another set of core texts belong to the philosophers of ancient Greece: Plato and Aristotle. It is impossible to overstate the impact these two thinkers have had on the West. They were not only central to European thought, but to Islamic philosophy as well.
* Why Greek?
Many credit ancient Greece with the origins of Western Civilization. European democracy, natural science, moral philosophy, statecraft, linguistics, and literary studies can all trace their origins to the ancient Greek-speaking world. Ancient Greek as a language seems particularly suited to philosophical studies and dialogue.

For the Western tradition, Greek was the original founding block not only of education, but of written language itself. All the writing systems of Europe are traced back to the Greek alphabet, so it is no surprise that the oldest surviving European literature is Greek.
* Why Latin?
Why should we study what was originally an obscure dialect spoken by a backwater tribe in central Italy? The Latins, through a long process of military and diplomatic expansion, grew to encompass the entire Mediterranean sea, which it held for 500 years. After the western half of their empire fell, Latin, the dominant language of most people, gradually evolved into the many languages spoken today: French, Spanish, Italian, Romanian, and many others. It continued as the international language of diplomacy, science, legal studies, and medicine for a thousand years after the fall of Rome.

It is also the liturgical language for a religion with 1.3 billion followers, namely the Catholic Church. Its use by that community has waned since the mid 20th century, but it is still the official language of the Roman Catholic Church.

Modern music actually developed out of traditional Latin-language music Gregorian chant, which developed into polyphonic music, and eventually into Classical music.
* What about English Classics?
English Classics, as distinct from Western Classics as a whole, are useful to us who are either part of or wish to understand the English-speaking world. As English is still a living, vernacular language, the canon continues to be in flux, with works being added or forgotten by each generation.
* What about non-Western Classics?
Other cultural spheres have their own Classical corpora. Perhaps the best counterpart to the Western Classics are the East Asian Classics, in that it is a greatly influential curriculum that can be traced back thousands of years.

It is under-utilized in the West, I believe, but it is understandable. Confucius is the center figure in the Eastern Canon, but was only first encountered by Western scholars in the 16th and 17th centuries when Jesuit missionaries ventured to China and began to translate Chinese literature.

The Western Classics were, of course, in a similar position in East Asia until those nations began a process of rapid modernization so that they could adapt to the new paradigm of a globalized world.
* What is the value?
As an interdisciplinary curriculum, there are many uses for Classical Studies. Learn about the roots of modern philosophy

*Learn about English.* One of the most practical uses of an education in Latin, but also Greek, is a much improved knowledge of English. Approximately 60% of English vocabulary is Latin or Greek in origin, having been borrowed directly or via an intermediary such as French, and the proportion is even larger in technical fields such as law, science, and medicine. It greatly helps knowledge of grammar, ability to read texts closely and develop a deep understanding of them, as well as to write clearly and effectively.

*Learn about Romance languages.* By studying Latin, one has a much easier time studying Romance languages. In graduate school, after only a single semester of “French for Reading Comprehension” and a minimal amount of studying, I was able to develop a surprising grasp of written French. I really only needed to recognize certain grammatical developments (e.g. the loss of the neuter gender) and certain phonetic shifts (e.g. the loss of intervocalic consonants). I can also understand the gist of something written in Italian or Spanish.

*Situate yourself in history.* Because Classical Studies is the study of a tradition, that is, a continuous handing off and interpretation of a set of ideas and practices from one generation to the next, when you read the Republic, you are not merely reading Plato, but you are taking part in a conversation with everyone else who has ever studied Plato. You are connected with Cicero, Augustine, Averroes, Thomas More, and even the creators of the Matrix. Many consider previous generations to be superstitious and backwards, such as believing the Earth to be flat until Columbus proved them wrong, but in fact we have had a rough estimate of its circumference since Eratosthenes measured it using only a stick and a pedestrian in about 240 BC. Natural philosophers debated the exact circumference for centuries

*Think deeply about big ideas.* Many of the texts deals with important questions. Who are we in the universe? What is the proper role of technology in our lives? What goals do I want to pursue? What is justice, and how can we bring it about? By studying them, you learn to think not just about the ideas, but learn novel ways of seeing them.

*Learn about the arts.* Beauty is one of the most sublime experiences in life. Learn about how artistic techniques change over time and how ideas of beauty differ from culture to culture. Learn how paintings draw on ancient ideals, how Western traditions of sculpture evolved and constantly looks back to its Greek origins. Theater is an ancient artform, with many roots in Greek tragedy and Greco-Roman comedy. See how Shakespeare took scenes and characters straight from playwrights such as Plautus or poets such as Ovid.

*Appreciate other cultures.* in the words of L.P. Hartley: “the past is a foreign country; they do things differently there.” While Classical Studies itself is concerned with the European Greco-Roman tradition, the skills and knowledge will allow you to understand other traditions as well. You will find studying even unrelated languages much easier. Other philosophical traditions and ways of thinking will be more accessible. You’ll have a keen eye for art.
